// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArnRNnIEpOCPjqGpuCQeLap6Y9VRIOFbI',
    appId: '1:932992869538:web:5349b574b3b994a922a3fb',
    messagingSenderId: '932992869538',
    projectId: 'shotspotdb',
    authDomain: 'shotspotdb.firebaseapp.com',
    storageBucket: 'shotspotdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe74GP3wqpDesRHlYfeJlnIMKCGwdNZJo',
    appId: '1:932992869538:android:e50fdee35484a29922a3fb',
    messagingSenderId: '932992869538',
    projectId: 'shotspotdb',
    storageBucket: 'shotspotdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOngAA8oHEA2p3BLuGh74EaglSQGoWX_E',
    appId: '1:932992869538:ios:f0fe2b1c1d208c3522a3fb',
    messagingSenderId: '932992869538',
    projectId: 'shotspotdb',
    storageBucket: 'shotspotdb.firebasestorage.app',
    iosBundleId: 'com.example.shotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOngAA8oHEA2p3BLuGh74EaglSQGoWX_E',
    appId: '1:932992869538:ios:f0fe2b1c1d208c3522a3fb',
    messagingSenderId: '932992869538',
    projectId: 'shotspotdb',
    storageBucket: 'shotspotdb.firebasestorage.app',
    iosBundleId: 'com.example.shotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArnRNnIEpOCPjqGpuCQeLap6Y9VRIOFbI',
    appId: '1:932992869538:web:a7d36fe3c549b88d22a3fb',
    messagingSenderId: '932992869538',
    projectId: 'shotspotdb',
    authDomain: 'shotspotdb.firebaseapp.com',
    storageBucket: 'shotspotdb.firebasestorage.app',
  );
}
